### ISSUE TITLE
Buildout falling when add new plone site

### ISSUE THREAD

**Issue by rodfersou** [collective/covertile.cycle2#8]
```
2015-05-19 09:14:55 ERROR Zope.SiteErrorLog 1432037695.070.813296636988 http://localhost:8080/@@plone-addsite
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.browser.admin, line 208, in __call__
  Module Products.CMFPlone.factory, line 105, in addPloneSite
  Module Products.GenericSetup.tool, line 365, in runAllImportStepsFromProfile
   - __traceback_info__: profile-covertile.cycle2:default
  Module Products.GenericSetup.tool, line 1119, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1030, in _doRunImportStep
   - __traceback_info__: plone.app.registry
  Module plone.app.registry.exportimport.handler, line 49, in importRegistry
  Module plone.app.registry.exportimport.handler, line 92, in importDocument
  Module plone.app.registry.exportimport.handler, line 212, in importRecord
ValueError: Cannot find a field for the record plone.app.tiles. Add a                 <field /> element or reference an interface and field name.
2015-05-19 09:14:55 ERROR ZServerPublisher exception caught
Traceback (most recent call last):
  File "/srv/cache/eggs/Zope2-2.13.22-py2.7.egg/ZServer/PubCore/ZServerPublisher.py", line 31, in __init__
    response=b)
  File "/srv/cache/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/Publish.py", line 455, in publish_module
    environ, debug, request, response)
  File "/srv/cache/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/Publish.py", line 276, in publish_module_standard
    if request is not None: request.close()
  File "/srv/cache/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/BaseRequest.py", line 218, in close
    notify(EndRequestEvent(None, self))
  File "/srv/cache/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/srv/cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/srv/cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/srv/cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
AttributeError: adapters
```

**Comment by djowett** [comment]
Oh, yes probably needs this line adding in metadata.xml.
Can you try it & let me know?

```
<dependency>profile-collective.cover:default</dependency>
```

Thanks

**Comment by hvelarde** [comment]
IMO this is the right way to do it: https://github.com/collective/collective.nitf/pull/124

I need to write a blog post on How to add a tile for collective.cover into your package

**Comment by djowett** [comment]
The blog post sounds a great way to spread the word.

I think this package is all working - apart from the "standard" RF test failure :-/
@hvelarde Was there anything specific in the above link that you think helps in this instance?

@rodfersou Can you give more info on this error please? Did you install c.cover before attempting to install this package?

**Comment by hvelarde** [comment]
@djowett RF test is failing locally also:

```
Failure in test Test Carousel Tile (test_carousel_tile.robot)
Traceback (most recent call last):
  File "/home/hvelarde/.buildout/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/hvelarde/.buildout/eggs/robotsuite-1.6.1-py2.7.egg/robotsuite/__init__.py", line 455, in runTest
    assert last_status == 'PASS', last_message
AssertionError: Element locator 'css=input.custom-title-input' did not match any elements after 30 seconds
```

**Comment by rodfersou** [comment]
@djowett I did your test and it worked!

I'll add this fix into my pull request, thank you

**Comment by djowett** [comment]
@hvelarde can you give me a screenshot of how this fails locally for you? As it's not doing so locally for me.  You can raise a new issue if you like.

(My fix above was for the line after)

**Comment by hvelarde** [comment]
@djowett I get the same error that is displayed on the [Travis build](https://travis-ci.org/collective/covertile.cycle2/builds/63220614).

**Comment by djowett** [comment]
Understood, but not much info for me to go on.   I'm after a screenshot if you have one?
